Feinkosthandel/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Feinkosthandel.Models;
using Feinkosthandel.Logic.DAL;

namespace Feinkosthandel.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _IndexLeft()
        {
            using (var db = new FeinkosthandelEntities())
            {
                var dbCategory = db.Category.ToList();
                List<CategoryVM> vmCatList = new List<CategoryVM>();

                foreach (var item in dbCategory)
                {
                    vmCatList.Add(new CategoryVM
                    {
                        id = item.Id,
                        name = item.Name
                    });
                }
                ViewBag.counter = vmCatList.Count();
                return PartialView(vmCatList);
            }
        }

        public ActionResult _IndexMain()
        {
            using (var db = new FeinkosthandelEntities())
            {
                var vmProducts = db.ProductInfo.ToList();
                List<ProductIndexVM> prodList = new List<ProductIndexVM>();
                foreach (var item in vmProducts)
                {
                    prodList.Add(new ProductIndexVM
                    {
                        Id = item.ProductId,
                        ProductName = item.Name,
                        Category = item.CategoryName,
                        UnitAmount = item.UnitAmount,
                        Manufacturer = item.ManufacturerName,
                        UnitPriceGross = item.UnitPriceGross ?? -1m,
                        Unit = item.UnitName,
                        UnitAbbreviation = item.UnitAbbreviation,
                        ImagePath = item.ImagePath,

                    });
                }
                return PartialView(prodList);
            }
        }
    }
}

Feinkosthandel/Views/Test/Index.cshtml
<div class="container">
    <div class="col-lg-2">
        @{
            Html.RenderAction("_IndexLeft", "Test");
         }
    </div>

    <div class="col-lg-10">
        @{ 
            Html.RenderAction("_IndexMain", "Test");
        }
    </div>
</div>

Feinkosthandel/Views/Test/_IndexLeft.cshtml
@model IEnumerable<Feinkosthandel.Models.CategoryVM>

<ul class="list-group">
    @foreach (var item in Model)
    {
        <li class="list-group-item">@item.name</li>
    }
</ul>

Feinkosthandel/Views/Test/_IndexMain.cshtml
@model IEnumerable<Feinkosthandel.Models.ProductIndexVM>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPriceGross)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitAbbreviation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Manufacturer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPriceGross)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Unit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitAbbreviation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>