Feinkosthandel/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Feinkosthandel.Logic;
using Feinkosthandel.Models;
using Feinkosthandel.Logic.DAL;

namespace Feinkosthandel.Controllers
{
    public class ShoppingCartController : Controller
    {
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            //Waren korb von user aus db laden
            var dbCart = ShoppingCartManager.LoadShoppingCartFromCustomer(int.Parse(User.Identity.Name));

            var vmCart = new List<ShoppingCartIndexVM>();
            //ViewModel erstellen/mappen


            foreach (var item in dbCart)
            {
                var vmItem = new ShoppingCartIndexVM()
                {
                    ShoppingCartId = item.ShoppingCartId,
                    ProductId = item.ProductId,
                    Name = item.ProductName,
                    ImagePath = item.ImagePath,
                    UnitAmount = item.UnitAmount,
                    UnitAbbreviation = item.Unit,
                    Manufacturer = item.ManufacturerName,
                    Amount = item.Amount,
                    LinePrice = Helper.GetLinePrice(item.UnitPrice, item.Amount, item.TaxRate)
                };

                vmCart.Add(vmItem);
            }
            //View anzeigen mit daten
            decimal summe = vmCart.Sum(a => a.LinePrice);
            ViewBag.summe = summe.ToString("0.00");

            return View(vmCart);
        }

        [Authorize]
        [HttpGet]
        public ActionResult RemoveProduct(int id)
        {
            var customerId = int.Parse(User.Identity.Name);
            bool success = ShoppingCartManager.Remove(customerId, id);

            if (success)
            {
                TempData["ErrorMessage"] = "Produkt erfolgreich aus Warenkorb entfernt";
                return RedirectToAction("Index", "Product");
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpGet]
        public ActionResult Add(int pid)
        {
            return Add(pid, 1);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Add(int pid, int amount)
        {
            var customerId = int.Parse(User.Identity.Name);
            bool success = ShoppingCartManager.Add(customerId, pid, amount);

            if (success)
            {
                TempData["ConfirmMessage"] = ShoppingCartManager.productadded(pid, amount);
                return RedirectToAction("Index", "Product");
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult FinishOrder()
        {
            return FinishOrder(new OrderFinish());
        }

        [HttpPost]
        public ActionResult FinishOrder(OrderFinish vmOrderFinish)
        {
            var dbshoppingCart = ShoppingCartManager.LoadShoppingCartFromCustomer(int.Parse(User.Identity.Name));
            var dbPaytypes = ShoppingCartManager.getPaymentType();
            var dbDelievertimes = ShoppingCartManager.getDelievery();

            OrderFinish orderfinsh = new OrderFinish();


            foreach (var item in dbshoppingCart)
            {
                var vmItem = new ShoppingCartIndexVM()
                {
                    ShoppingCartId = item.ShoppingCartId,
                    ProductId = item.ProductId,
                    Name = item.ProductName,
                    ImagePath = item.ImagePath,
                    UnitAmount = item.UnitAmount,
                    UnitAbbreviation = item.Unit,
                    Manufacturer = item.ManufacturerName,
                    Amount = item.Amount,
                    LinePrice = Helper.GetLinePrice(item.UnitPrice, item.Amount, item.TaxRate)
                };

                orderfinsh.ShoppingCart.Add(vmItem);
            }

            decimal totalprice = orderfinsh.ShoppingCart.Sum(a => a.LinePrice);

            orderfinsh.ProductsTotal = totalprice;            
            orderfinsh.TotalPrice = totalprice+ Helper.CalculateCharges(vmOrderFinish.OrderId, vmOrderFinish.Payment, vmOrderFinish.DelieveryDate, vmOrderFinish.Delievery);

            foreach (var item in dbPaytypes)
            {
                var vmItem = new PaymentTypeVM()
                {
                    PaymentTypeId = item.Id,
                    PaymentTypeName = item.Name
                };

                orderfinsh.PaymentTypeList.Add(vmItem);
            }

            foreach (var item in dbDelievertimes)
            {
                var vmItem = new DelieveryTimeVM()
                {
                    DelieverTimeId = item.Id,
                    DelieverTimeName = item.Name,
                    From = item.From,
                    To = item.To
                };
                orderfinsh.DelieveryTimeList.Add(vmItem);
            }

            var dbCustomer = ShoppingCartManager.getCustomerInfo(int.Parse(User.Identity.Name));

            orderfinsh.RechnungsStreet = dbCustomer.Street;
            orderfinsh.RechnungsCity = dbCustomer.City;
            orderfinsh.RechnungsZip = dbCustomer.Zip;

            orderfinsh.Lieferadresse = dbCustomer.Street;
            orderfinsh.LieferCity = dbCustomer.City;
            orderfinsh.LieferZip = dbCustomer.Zip;

            orderfinsh.Titel = dbCustomer.Title;
            orderfinsh.Vorname = dbCustomer.FirstName;
            orderfinsh.Nachname = dbCustomer.LastName;

            orderfinsh.Delievery = 6;

            orderfinsh.OrderId = ShoppingCartManager.GetShoppingCartId(int.Parse(User.Identity.Name));

            DateTime deliveryDefaultValue = DateTime.Now;

            if ((int)deliveryDefaultValue.AddDays(3).DayOfWeek == 6)
                ViewBag.date = deliveryDefaultValue.AddDays(5).ToString("yyyy-MM-dd");
            else if ((int)deliveryDefaultValue.AddDays(3).DayOfWeek == 0)
                ViewBag.date = deliveryDefaultValue.AddDays(4).ToString("yyyy-MM-dd");
            else
                ViewBag.date = deliveryDefaultValue.AddDays(3).ToString("yyyy-MM-dd");

            //Überprüfen ob wert aus dem request kommen und behalten

            if (!string.IsNullOrEmpty(vmOrderFinish.Lieferadresse))
            {
                orderfinsh.Lieferadresse = vmOrderFinish.Lieferadresse;
            }
            if (!string.IsNullOrEmpty(vmOrderFinish.LieferCity))
            {
                orderfinsh.LieferCity = vmOrderFinish.LieferCity;    
            }
            if (vmOrderFinish.LieferZip!=default(int))
            {
                orderfinsh.LieferZip = vmOrderFinish.LieferZip;
            }
            if(vmOrderFinish.Delievery!=default(int))
            {
                orderfinsh.Delievery = vmOrderFinish.Delievery;
            }
            if (vmOrderFinish.Payment!=default(int))
            {
                orderfinsh.Payment = vmOrderFinish.Payment;
            }
            if (vmOrderFinish.DelieveryDate != default(DateTime))
            {
                ViewBag.date = vmOrderFinish.DelieveryDate.ToString("yyyy-MM-dd");
            }

            return View(orderfinsh);
            
        }

        [HttpPost]
        [Authorize]
        public ActionResult FinalizeOrder(OrderFinish vmOrderFinish)
        {
            //vmOrderFinish.DelieveryDate Tag?
            string tag = vmOrderFinish.DelieveryDate.DayOfWeek.ToString();

            //GEsamtpreis berechnen (Aufschläge berücksichtigen)
            var success = OrderManager.PlaceOrder(
                int.Parse(User.Identity.Name),
                vmOrderFinish.Payment,
                vmOrderFinish.DelieveryDate,
                vmOrderFinish.Delievery,
                vmOrderFinish.Lieferadresse,
                vmOrderFinish.LieferCity,
                vmOrderFinish.LieferZip);
            //Aus Warenkorb eine Bestellung machen (Neue Adresse falls geändert berücksichtigen)
            //Dem Benutzer eine Danke Seite anzeigen
            if (!success)
            {
                return RedirectToAction("Index", "Home");
            }


            return RedirectToAction("Thanks", new { id = vmOrderFinish.OrderId });
        }

        [HttpGet]
        [Authorize]
        public ActionResult Thanks(int id)
        {
            //id = OrderId 
            using (var db = new FeinkosthandelEntities())
            {
                var x = db.GetOrderInfo.ToList();
                ThanksVM vmThanks = new ThanksVM();
                var dbOrderInfo = db.GetOrderInfo.Where(o => o.OrderId == id).First();

                vmThanks.City = dbOrderInfo.City;
                vmThanks.Date = dbOrderInfo.Date;
                vmThanks.From = dbOrderInfo.From;
                vmThanks.To = dbOrderInfo.To;
                vmThanks.Street = dbOrderInfo.Street;
                vmThanks.TotalPriceGross = dbOrderInfo.TotalGross;
                vmThanks.Zip = dbOrderInfo.Zip;
                vmThanks.PaymentName = dbOrderInfo.Name;
                return View(vmThanks);
            }
            //gesucht Lieferdatum, Lieferzeitpunkt, Gesamtpreis

        }

        public ActionResult SearchIndex(string searchstring, int searchCat)
        {
            Session["selectionsearch"] = searchstring;
            Session["selectioncat"] = searchCat;

            var filteredList = ProductManager.getAllProducts()
                .FindAll(x => (x.CategoryName.ToLower().Contains(searchstring.ToLower()) || 
                    x.Name.ToLower().Contains(searchstring.ToLower()) || 
                    x.ManufacturerName.ToLower().Contains(searchstring.ToLower()) || 
                    x.Description.ToLower().Contains(searchstring.ToLower()))
                    && (searchCat!=0? x.CategoryId == searchCat:x.CategoryId!=0)
                    );

            var vmProducts = new List<ProductIndexVM>();

            foreach (var dbProduct in filteredList)
            {

Feinkosthandel/Views/ShoppingCart/FinishOrder.cshtml
@model Feinkosthandel.Models.OrderFinish

@{
    ViewBag.Title = "FinishOrder";
}

<form method="post">
    <h2>Bestellung</h2>
    <div class="row">
        <div class="col-lg-3">
            <div class="panel panel-primary">
                <div class="panel-heading">

                    <h2 class="panel-title">Ihr Warenkorb</h2>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <tr>
                            <th width="70px">Amount</th>
                            <th width="200px">Product</th>
                            <th style="text-align:center">Price</th>
                        </tr>
                        @foreach (var item in Model.ShoppingCart)
                        {
                            <tr>
                                <td style="text-align:center">@item.Amount x</td>
                                <td>@item.Name</td>
                                <td style="text-align:center">€ @(item.LinePrice.ToString("0.00")) ,-</td>
                            </tr>
                        }
                        <tr>
                            <td colspan="3">Produktgesamtpreis: € @(Model.ProductsTotal.ToString("0.00")) ,-</td>
                        </tr>
                        <tr>
                            <td colspan="3">Gesamtsumme: € @(Model.TotalPrice.ToString("0.00")) ,-</td>
                        </tr>

                    </table>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2 class="panel-title">Rechnungsadresse</h2>
                </div>

                <div class="panel-body">
                    <div class="mypanelfontsize">@Model.Titel @Model.Nachname @Model.Nachname ID: @Model.OrderId</div>
                    <div class="mypanelfontsize">@Model.RechnungsStreet, @Model.RechnungsZip @Model.RechnungsCity</div>
                </div>
            </div>


            <div class="panel panel-primary">
                <div class="panel-heading">

                    <h2 class="panel-title">Lieferadresse falls abweichend</h2>
                </div>
                <div class="panel-body">
                    <div class="form-group myformheights">
                        @Html.LabelFor(model => model.Lieferadresse, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Lieferadresse, new { htmlAttributes = new { @class = "form-control mytextboxconfig", @Value = @Model.Lieferadresse, placeholder = "Street" } })
                            @Html.ValidationMessageFor(model => model.Lieferadresse, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group myformheights">
                        @Html.LabelFor(model => model.LieferZip, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LieferZip, new { htmlAttributes = new { @class = "form-control mytextboxconfig", @Value = Model.LieferZip, placeholder = "Street" } })
                            @Html.ValidationMessageFor(model => model.LieferZip, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group myformheights">
                        @Html.LabelFor(model => model.LieferCity, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LieferCity, new { htmlAttributes = new { @class = "form-control mytextboxconfig", @Value = Model.LieferCity, placeholder = "Street" } })
                            @Html.ValidationMessageFor(model => model.LieferCity, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Liefer- und Zahlungsmethode</h3>
                </div>
                <div class="panel-body">
                    <!--Styles in productinfo.css-->
                    <dl class="dl-horizontal mydlgroup">
                        <dt>Lieferdatum:</dt>
                        <dd>
                            <input type="date" name="@nameof(Model.DelieveryDate)" value="@ViewBag.date" min="@DateTime.Now.AddDays(1).ToString("yyyy-MM-dd")" 
                                   onchange="this.form.submit()"/>
                        </dd><!--YYYY-MM-DD  ... DD/MM/YYYY-->
                        <hr />
                        <dt>Lieferzeitpunkt:</dt>
                        <dd>
                            <select class="" id="DelieveryTime" name="@nameof(Model.Delievery)" style="height:30px" onchange="this.form.submit()">
                                @foreach (var item in Model.DelieveryTimeList)
                                {
                                    
                                    <option value="@item.DelieverTimeId" @((item.DelieverTimeId == Model.Delievery) ? "selected" : "")>@item.DelieverTimeName @(item.From):@(item.To)</option>
                                    
                                }

                            </select>
                        </dd>
                        <hr />
                        <dt>Zahlungsart:</dt>
                        <dd>
                            <select class="" id="PaymentType" name="@nameof(Model.Payment)" style="height:30px" onchange="this.form.submit()">
                                @foreach (var item in Model.PaymentTypeList)
                                {
                                    <option value="@item.PaymentTypeId"@((item.PaymentTypeId == Model.Payment) ? "selected" : "")>@item.PaymentTypeName</option>
                                }
                            </select>
                        </dd>
                        <hr />
                    </dl>

                    <p>

                    </p>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-9"></div>
        <div class="col-lg-1">
            <div class="form-group">
                <input type="button" class="btn btn-default" value="Zurück" onclick="location.href='@Url.Action("Index", "ShoppingCart")'" />
            </div>

        </div>
        <div class="col-lg-2">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Bezahlen" formaction="FinalizeOrder"/>
            </div>
        </div>
    </div>
    <input type="hidden" name="@nameof(Model.OrderId)" value="@Model.OrderId" />
    <input type="hidden" name="@nameof(Model.RechnungsCity)" value="@Model.RechnungsCity" />
    <input type="hidden" name="@nameof(Model.RechnungsStreet)" value="@Model.RechnungsStreet" />
    <input type="hidden" name="@nameof(Model.RechnungsZip)" value="@Model.RechnungsZip" />
</form>

Feinkosthandel/Views/ShoppingCart/Index.cshtml
@model IEnumerable<Feinkosthandel.Models.ShoppingCartIndexVM>

@{
    ViewBag.Title = "Index";
}

<style>
    td {
        color: brown;
    }

    .gespreis {
        border:groove;
        border-width:10px;
        color:brown;
        font-size:x-large;
        text-align:center;
    }
</style>

<h2>Mein Einkaufswagerl</h2>


<table class="table table-hover" style="background-color:rgba(164, 147, 147, 0.48)">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitAmount)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LinePrice)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src="@Url.Content(item.ImagePath)" alt="B" style="height:50px;width:50px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitAmount) @Html.DisplayFor(modelItem => item.UnitAbbreviation)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LinePrice)
            </td>
            <td>
                <button type="button" onclick="location.href='@Url.Action("Details", "Product",new { id = item.ProductId })'" class="btn btn-default">Details</button>
                <button type="button" onclick="location.href='@Url.Action("RemoveProduct","ShoppingCart", new { id = item.ProductId })'" class="btn btn-default">Delete</button>
                @*@Html.ActionLink("Details", "Details", "Product", new { id = item.ProductId }, new { area = "" }) |
                    @Html.ActionLink("Delete", "RemoveProduct", new { id = item.ProductId })*@
            </td>

        </tr>

    }
</table>

<div class="gespreis">
    <p style="color:brown"><b>Gesamtpreis: € @ViewBag.summe ,-</b></p>
</div>
<p><button type="button" onclick="location.href='@Url.Action("FinishOrder", "ShoppingCart")'" class="btn btn-default">Zur Bestellung</button></p>

Feinkosthandel/Views/ShoppingCart/SearchIndex.cshtml
@model IEnumerable<Feinkosthandel.Models.ProductIndexVM>


<div style="padding-top:50px">

    <table class="table table-hover" id="example" style="padding-top:120px; background-color:rgba(164, 147, 147, 0.48)">
        <tr>
            <th width="150px">
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th width="200px">
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th width="200px">
                @Html.DisplayNameFor(model => model.Manufacturer)
            </th>
            <th width="200px">
                @Html.DisplayNameFor(model => model.UnitPriceGross)
            </th>


            <th width="150px">
                @Html.DisplayNameFor(model => model.UnitAmount)
            </th>
            <th width="150px">
                Picture
            </th>
            <th width="100px">Details</th>
            <th width="250px">ShoppingCart</th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manufacturer)
                </td>
                <td>
                    € @Html.DisplayFor(modelItem => item.UnitPriceGross) ,-
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.UnitAmount) @Html.DisplayFor(modelItem => item.UnitAbbreviation)
                </td>
                <td>
                    <img src="@Url.Content(item.ImagePath)" alt="B" style="height:50px;width:50px;" />
                </td>
                <td>
                    <a href="/Product/Details/@item.Id"><span style="font-size:2.5em;" class="glyphicon glyphicon-eye-open"></span></a>
                </td>

                <td>
                    <form method="post" action="/ShoppingCart/Add">
                        <!--<a href="/ShoppingCart/Add"><span style="font-size:2.5em;" class="glyphicon glyphicon-shopping-cart"></span></a>-->
                        <div class="qty">

                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                            </button>
                            <input type="hidden" name="pid" value="@item.Id" />


                            <span id="imagehover" class="minus" onclick="countminus(@item.Id)">-</span>
                            <span><input type="text" class="count" id="@(item.Id+"amountcounter")" name="amount" value="1" style="width:55px; text-align:center" /></span>
                            <span id="imagehover" class="plus" onclick="countplus(@item.Id)">+</span>
                        </div>
                    </form>
                </td>

            </tr>
        }

    </table>
</div>

Feinkosthandel/Views/ShoppingCart/Thanks.cshtml
@model Feinkosthandel.Models.ThanksVM

@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks for Shopping ;)</h2>
<p>Ihr Gesamtpreis beträgt: - @Model.TotalPriceGross</p>
<p>Ihre Bestellung wird am: - @Model.Date.ToShortDateString() zwischen @Model.From Uhr und @Model.To Uhr geliefert</p>
<p>Ihre Bezahlungsart ist - @Model.PaymentName</p>
<p>@ViewBag.thanks</p>