Feinkosthandel/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Feinkosthandel.Logic;

namespace Feinkosthandel.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult Index2(int id)
        {
            if (id==1)
            {
                ViewBag.Win = GameManager.didWin();
                return RedirectToAction("Winner");
            }
            return RedirectToAction("NoWinner");
        }

        public ActionResult Winner()
        {
            return View();
        }

        public ActionResult NoWinner()
        {
            return View();
        }
    }
}

Feinkosthandel/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Feinkosthandel.Models;
using Feinkosthandel.Logic;

namespace Feinkosthandel.Controllers
{
    public class NavigationController : Controller
    {
        // GET: Navigation
        public ActionResult Menu()
        {
            List<CategoryVM> catlist = ProductManager.getAllCategories();
            return PartialView("_Navigation",catlist);
        }

        public ActionResult Cats()
        {            
            var selCat = 0;
            Session["selectionsearch"] = string.IsNullOrEmpty((string)Session["selectionsearch"]) ? "" : Session["selectionsearch"];
            try
            {
                selCat = (int)Session["selectioncat"];
            }
            catch
            {
                selCat = 0;
            }
            finally
            {
                Session["selectioncat"] = selCat;
            }

            CategorySearchVM catSearcher = new CategorySearchVM();
            catSearcher.Catlist.Add(new CategoryVM() { id = 0, name = "Alle" });
            List<CategoryVM> liste = ProductManager.getAllCategories();
            foreach (var item in liste)
            {
                catSearcher.Catlist.Add(item);
            }
            
            catSearcher.CatSelected = 0;
            catSearcher.categoryName = "";
            if (catSearcher.CatSelected != default(int))
                catSearcher.CatSelected = (int)TempData["selectioncat"];
            if (!string.IsNullOrEmpty(catSearcher.categoryName))
                catSearcher.categoryName = TempData["selectionsearch"] as string;
            return PartialView("_Categories",catSearcher);
        }
    }
}

Feinkosthandel/Views/Shared/_Categories.cshtml
@model Feinkosthandel.Models.CategorySearchVM
@using (Html.BeginForm("Index", "ShoppingCart/SearchIndex", FormMethod.Get))
{
    int selCat = (int)Session["selectioncat"];
    string selSearch = Session["selectionsearch"] as string;


    <select name="searchCat" style="color:black" onchange="this.form.submit()">        
        @foreach (var item in Model.Catlist)
        {
            <option  value="@item.id" @(item.id==selCat?"selected":"")>@item.name</option>
        }
    </select>
    <ul class="nav navbar-nav">
        <li>@Html.TextBox("searchstring", ViewBag.CurrentFilter as string, new { @class = "form-control", onchange="this.form.submit()", @Value = selSearch})</li>
        <li><input type="submit" value="Search" class="btn btn-default" /></li>
    </ul>
}

Feinkosthandel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meine ASP.NET-Anwendung</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body style="padding-top: 36px; padding-left:0px; display:flex; justify-content:flex-end ">
    @Html.Partial("_LayoutNavBar");
    <div class="container body-content">
        <div class="col-md-1 bg-primary" style="height:650px">
            @Html.Action("Menu", "Navigation")
        </div>
        <div class="col-md-11">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hofbauer's Feinkost Shop Deluxe</p>
        </footer>

    </div>
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>*@


 
        


    @RenderSection("jsscripts", required: false)

    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-top-right",
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "3000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        $(document).ready(function () {

            @if (TempData["ErrorMessage"] != null)
            {
                <text>
            toastr.error("", "@TempData["ErrorMessage"]");
            </text>
            }

            @if (TempData["ConfirmMessage"] != null)
            {
                <text>
            toastr.success("", "@TempData["ConfirmMessage"]");
            </text>
            }

            });
    </script>

</body>
</html>

Feinkosthandel/Views/Shared/_LayoutNavBar.cshtml
<style>
    a.myhyper {
        color: #ffffff;
        font-size: large;
    }

    a:hover {
        color: black;
    }

    li > a:hover {
        color: black;
        text-decoration: none;
        background-color: transparent !important;
    }
</style>

<div class="navbar bg-primary navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">

            @Html.ActionLink("Anwendungsname", "Index", "Home", new { area = "" }, new { @class = "navbar-brand myhyper" })
        </div>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Logout", "Logout", "Account", new { area = "" }, new { @class = "myhyper" })</li>
                }
                else
                {
                    <li>@Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "myhyper" })</li>
                    <li>@Html.ActionLink("Registrieren", "Register", "Account", new { area = "" }, new { @class = "myhyper" })</li>
                }
            </ul>
        </div>
        <div class="navbar-right" style="padding:10Px">

            @Html.Action("Cats", "Navigation")

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">


                @if (User.Identity.IsAuthenticated)
                {


                    <li>@Html.ActionLink("Produkte", "Index", "Product", new { area = "" }, new { @class = "myhyper" })</li>
                    <li>@Html.ActionLink("Gewinnspiel", "Index", "Game", new { area = "" }, new { @class = "myhyper" })</li>
                    <li>@Html.ActionLink("Einkaufswagerl", "Index", "ShoppingCart", new { area = "" }, new { @class = "myhyper" })</li>

                }
                else
                {
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "myhyper" })</li>

                }
            </ul>
        </div>

    </div>
</div>

Feinkosthandel/Views/Shared/_LayoutSideMenu.cshtml
<ul>
    <li><a href="/Product/Index/1">Käse</a></li>
    <!--in product controller int id erweitern und listenrückgabe pro categorie änder-->
    <li>Wurst</li>
    <li>Getränke</li>
    <li>Obst</li>
</ul>

Feinkosthandel/Views/Shared/_LeftContent.cshtml
@section list 
{
    @{ Html.RenderAction("_IndexLeft", "Product");}
    }

Feinkosthandel/Views/Shared/_Navigation.cshtml
@model IEnumerable<Feinkosthandel.Models.CategoryVM>



<h3 style="padding-top:30px">Kategrien</h3>


    @foreach (var item in Model)
    {
        <a style="text-decoration:none" href="/Product/Index/@item.id">
            <li class="list-group-item mylisthover" style="color:black">
                @item.name.Substring(0,item.name.Length<=7?item.name.Length:7)
                <span class="badge badge-primary badge-pill">@item.productcounter</span>
            </li>

        </a>
        
    }